package com.sunbeam.rest.webservices.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.sunbeam.rest.webservices.dao.UserDao;
import com.sunbeam.rest.webservices.pojo.User;
import com.sunbeam.rest.webservices.utilities.SendMailTLS;
import com.sunbeam.rest.webservices.utilities.SendSms;

@Service
public class UserService
{
	@Autowired
	private UserDao dao;
	
	public User authenticate(String email, String pass)
	{
		try
		{
			User user = dao.authenticate(email);
			if (user!=null && user.getPass().equals(pass))
				return user;
		} 
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return null;
	}
	
	public int insertUser(User obj) 
	{
		try 
		{
			return dao.insertUser(obj);
		} 
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return -1;
	}
	
	public User updateUser(User user) 
	{
		try 
		{
			return dao.updateUser(user);
		} 
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return null;
	}
	
	public User updatePassword(User user) 
	{
		try 
		{
			return dao.updatePassword(user);
		} 
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return null;
	}
	
	public int forgotPassword(String email) 
	{
		try 
		{
			User user = dao.authenticate(email);
			if(user!=null)
			{
				String msg = "Hello "+email+",\n\n\n Your password for Campus portal account is \""+user.getPass()+"\"\n\n\n\n\t -****This mail is generated by Campus Portal!";
				SendMailTLS sendMailTLS = new SendMailTLS();
				if(sendMailTLS.mailMe(email, msg) == true)
				{
					SendSms.init();
					SendSms.server = "http://127.0.0.1:8800/";
					SendSms.user = "nikshah41";
					SendSms.password = "nikshah41";
					SendSms.phonenumber = user.getMobileno();
					SendSms.text = "Hello,\n Your password for Campus portal account is \""+user.getPass()+"\"";
					SendSms.send();
					
					return 1;
				}
				return -1;
			}
		} 
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return -1;
	}
}


