package com.sunbeam.rest.webservices.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.sunbeam.rest.webservices.dao.HomeDao;
import com.sunbeam.rest.webservices.pojo.Contact;
import com.sunbeam.rest.webservices.utilities.SendMailTLS;

@Service
public class HomeService
{
	@Autowired
	private HomeDao dao;
	
	public void insertConatct(Contact obj) 
	{
		try 
		{
			dao.insertConatct(obj);
			String msg = "Thank You for contacting us,\n\nWe will get back to you as soon as possible!!\n\n\n\t -This mail is generated by Campus Portal!!";
			SendMailTLS sendMailTLS = new SendMailTLS();
			sendMailTLS.mailMe(obj.getEmail(),msg);
		} 
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
}


